baseURL = "https://www.sat.car2x.org/"
languageCode = "en-us"
title = "space_Veins"
theme = "space_Veins"
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4
